version: "3.5"

services:
  backend:
    build:
      context: .
      dockerfile: back.Dockerfile
    container_name: bio-summ-back
    restart: unless-stopped
    ports:
      - 8000:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  frontend:
    build:
      context: .
      dockerfile: front.Dockerfile
      args:
        PORT: "8001"
        BACKEND_URL: "http://localhost:8000"
        BACKEND_SOCKET: "ws://localhost:8000"
        BACKEND_SOCKETIO_PATH: "/ws/socket.io"
    container_name: bio-summ-front
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - 8001:8001